apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bv31gnafx-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:942dabebfed07ac2aafa7f82894a60c9a3b5a95b@sha256:7b61062c4c915ee88390592ddac9e91e8cbaa2fc2e0723c50ff0369e5d76790d
          name: container-image
